### ISSUE TITLE
Fatal error: Cannot redeclare wptexturize()

### ISSUE THREAD

**Issue by skaltenegger** [infinum/decoupled-json-content#26]
Hey there,

Your plugin looks amazing, that's why I tried to install it on my local machine, did the following:
1) cloned the repo and renamed it to `decoupled-json-content`
2) ran `composer -o dump-autoload` in plugin root
3) copied the plugin folder into the plugins directory of wordpress
4) My local WP version is `5.1.1`

Unfortunately now, when I access `/wp-content/plugins/decoupled-json-content/page/rest-routes/page.php` in my browser I get the following error message:
```
Fatal error: Cannot redeclare wptexturize() (previously declared in /Applications/MAMP/htdocs/project/wp-includes/formatting.php:51) in /Applications/MAMP/htdocs/project/wp-includes/formatting.php on line 315
```

Do you have any idea why I'm getting this error? Any help is much appreciated!

Thanks a lot,
Stefan

**Comment by dingo-d** [comment]
This is odd, as there is no `wptexturize` in that file 🤷‍♂️

**Comment by skaltenegger** [comment]
Thanks @dingo-d for your quick reply. I agree, this is indeed odd. 

I just deactivated all other plugins and used the twenty nineteen standard theme, unfortunately still getting the same error. 
Would you mind creating a ZIP of the plugin for me so that I can try to install your version? 
Are you successfully using the plugin on Wordpress version greater or equal 5.1? 

Thanks so much, appreciate your help with this!
Stefan

**Comment by dingo-d** [comment]
Just a check, did you provide a `?slug=&type=` as a query parameter to `page.php`?

**Comment by skaltenegger** [comment]
I did, the URL looks like this in my case: 
`http://mywebsite.local/wp-content/plugins/decoupled-json-content/page/rest-routes/page.php?slug=my-slug&type=post?`
Does that look good to you?

**Comment by dingo-d** [comment]
The last `?` isn't necessary. Do you have pretty permalinks enabled? Also try clearing transients.

I'll test this with the latest WP and get back to you, not sure if anything broke in the meantime.

**Comment by skaltenegger** [comment]
I have pretty permalinks enabled and set to `Post name`. Thanks for testing and for getting back to me then!

**Comment by dingo-d** [comment]
I can confirm that there is some kind of a bug. I got 

```php
Fatal error: Cannot redeclare maybe_hash_hex_color() (previously declared in /srv/www/personal/wordpress-test/public_html/wp-includes/formatting.php:5826) in /srv/www/personal/wordpress-test/public_html/wp-includes/formatting.php on line 5826
```

It could be coming from Gutenberg. Not 100% sure.

@iruzevic Do you know why this would happen?

**Comment by marcof-git** [comment]
It seems that WPINC is null. I solved with 
`require_once filter_var( $parse_uri[0] . 'wp-includes' . '/formatting.php', FILTER_SANITIZE_STRING );`

**Comment by dingo-d** [comment]
Glad to see you solving this issue 🙂
